### PR TITLE
OpenGl-WindowClasses

### PR DESCRIPTION
**Pull request by FunniNam3**

### CODE REVIEW

**Review by aabuyazid — APPROVED** [review]
Camera debug works for me. I approve of it

**Review by aabuyazid — CHANGES_REQUESTED** [review]
On second thought, do you think you can merge with Yaml first?

**Review by aabuyazid — APPROVED** [review]

**Comment by aabuyazid** [comment]
I successfully merge Ethan's and Roei's contributions. @Fanfania333 @FunniNam3 @Bobby547, please check to see if the merge is successfully for you guys.

**Comment by FunniNam3** [comment]
I did a whoops but I fixed it

**Review by Fanfania333 — APPROVED** [review]
Writing an invalid location while adding a game object crashes the program. We should probably add a validation system to that. We need better descriptions for the properties of the camera. Can't add lights or cameras, but that is not implemented yet I think? Also the light intensity doesn't seem to be doing anything. These are all issues that can be fixed later though. The camera movement, light editing, deleting and adding objects seems to work great so approving the pull.

**Pull request merged**
